### ISSUE TITLE
Feedback project 2 Data-dashboard

### ISSUE THREAD

**Issue by AmaliaRiveraC** [sanrey254/proyecto-2-data-dashboard#13]
1. Documentación: la explicación sobre las decisiones de diseño creo que pudiera ser más elaborada no sólo lo que toman de la marca sino el porque de las otras decisiones distintas al color y a la tipografía que se han tomado.
2. JS:  Semántica/Nomenclatura hay un trabajo muy bueno en el nombramiento de variables, sólo unos pequeños detalles con algunos nombres de variables como los contadores countY, countI en el archivo data.js y en main.js en un momento nombras studentsObject a un Array. 
2. Estilo (eslint): Incluyeron la guía de estilos, muy bien! Para el próximo proyecto les recomiendo correr el comando de npm run test y npm run eslint y ahí podrán ver y después corregir los warnings que les está lanzando según la propia guía de estilos que incluyen.
3. Github: se espera el uso de issues y milestones, hubo un taller con Alexandra para este tema de los issues en github , serie de issues como guía para el desarrollo de tareas y/o de problemas y creación y uso de milestones. Pongan atención en este punto de la rúbrica para llegar al nivel, no tiene mucha dificultad y les ayudará a su planificación
4. Git: Las he dejado en nivel 3 pero Jazmin pon atención en la convención que utiliza Brenda en los commits, idealmente deberían de acordar esto al principio de sus proyectos con su equipo de trabajo ¿cuál será el estándar para la escritura de commits en github?
5. Lógica: casi no hay código muerto, sólo en la línea de data.js declaras la variable statusGeneration y su valor nunca se lee, lo mismo para la variable stats en la línea 125, donde realmente ocupas stats de la línea 135. En el archivo main.js en la línea 123 declaras una variables result que nunca ocupas.  Detalles perfectibles!
6. UX: Entrevistas: Les recomiendo documentar todo el proceso de entrevistas, en este momento sólo están adjuntando el cuestionario que hicieron pero sería  bueno documentar también las respuestas que obtuvieron, si hacen entrevistas en ambientes controlados grabaciones de audio y/o vídeo. Bien por el formato de la encuesta, bastante profesional. 
*Bien por las buenas prácticas, cuidado con el uso de acentos invertidos. Cuidado con las rutas de imágenes en el README de la carpeta UX, las imágenes no se visualizan porque las rutas deberían de contemplar el punto dónde está colocado el el archivo README (ej. para las imágenes dentro de la carpeta UX sería './img/tablerosexistentes.png'  don de el punto ./ indica que en esa carpeta donde estamos colocados accedemos a la carpeta img, o para las imágenes dentro de la carpeta src '../src/img/sketch1.png' donde los dos puntos ../ que indica que saliendo de la carpeta donde estamos y entrando después la carpeta src).

*Muy buen trabajo en términos técnicos! La presentación la pude ver y también me gustó. Bien salvadas las preguntas que les hicieron, a pesar de todos estos puntos buenos me gustaría sugerir que para los próximos proyectos nos preocupemos un poco más por el aprendizaje conjunto y colaborativo con las personas involucradas en el proyecto, tratar de llevar estos logros al trabajo en equipo y buscar avanzar a las mismas velocidades. Sigan trabajando duro! Un saludo.

**Comment by jaztan** [comment]
Muchas gracias.

**Comment by brendasanrey** [comment]
Haré las correcciones y tomaré en cuenta las indicaciones. Gracias por el feedback.
